### PR TITLE
meta-clang: Update to latest HEAD

### PR DESCRIPTION
**Pull request by avalluri**
As per @mythi request,  Updates the meta-clang submodule.

Signed-off-by: Amarnath Valluri amarnath.valluri@intel.com

### CODE REVIEW

**Comment by mythi** [comment]
@avalluri we're using 'krogoth'. Let's not update to clang 3.9 but keep 3.8 from krogoth. The correct commit is `dc1d9d550a5d33d76a3bc6162739edccbd8bf012`

**Comment by avalluri** [comment]
@mythi  I got it now, i updated to krogoth HEAD, is 857d8e02130a21d80728950f757c0a9e418db60d. I couldn't find the commit you pointed.

**Comment by mythi** [comment]
On Thu, Sep 8, 2016 at 11:03 AM, Amarnath Valluri notifications@github.com
wrote:

> @mythi https://github.com/mythi I got it now, i updated to kgrogth
> HEAD, is 857d8e02130a21d80728950f757c0a9e418db60d. I couldn't find the
> commit you pointed.

krogoth has my PR merged which is why we'd need this PR:
https://github.com/kraj/meta-clang/commit/dc1d9d550a5d33d76a3bc6162739edccbd8bf012

**Comment by avalluri** [comment]
@mythi, i altered the PR to point to your commit

**Comment by mythi** [comment]
thanks!

**Comment by mythi** [comment]
@avalluri could you rebase this please

**Pull request merged**
