### PR TITLE
Jenkinsfile: use EMAIL instead of GIT_COMMMITTER_EMAIL

### PR DESCRIPTION
**Pull request by okartau**
The idea is to cover also GIT_AUTHOR_EMAIL

### CODE REVIEW

**Comment by kad** [comment]
:-1: 
what is use case for it ?

**Comment by okartau** [comment]
I thought you turn it down. BTW, both GIT_COMMITTER_ settings right now seem to be redundant in Jenkinsfile, as same values come from Jenkins main env vars section, and get passed into docker session. With current PR we actually get 3 values, with EMAIL added

**Comment by kad** [comment]
Generally, this variable here has bigger preference, as it allows jobs to control more precisely this parameter. Having more parameters set via jenkins global/node variables complicates setup and makes it less transparent.

**Comment by okartau** [comment]
don't merge, this is not right way to handle the situation (using test-build label to indicate this)

**Pull request closed without merging**
