### PR TITLE
libyami: Add support for YAMI

### PR DESCRIPTION
**Pull request by rojkov**
Addresses https://github.com/ostroproject/ostro-os/issues/164
@laxigithub please test if this PR helps to avoid gstreamer-plugins-bad

### CODE REVIEW

**Comment by mythi** [comment]
retest this please

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
retest this please

**Comment by okartau** [comment]
This keeps failing, there are some fuzzy errors that dont repeat well, but seems after
getting past random failures points sometimes,
the build fails in repeating manner with LIC checksum QA error:
ERROR: libyami-utils-0.1.0-r0 do_populate_lic: QA Issue: libyami-utils: The LIC_FILES_CHKSUM does not 
match for file://LICENSE;md5=3b83ef96387f14655fc854ddc3c6bd57

## 00:04:44.586 libyami-utils: The new md5 checksum is e3fc50a88d0a364313df4b21ef20c29e

The 3b83ef... is md5 sum of libyami/COPYING.LIB
and is specified in bb file added by current PR change.
LIC_FILES_CHKSUM = "file://COPYING.LIB;md5=3b83ef96387f14655fc854ddc3c6bd57"
(note that there is no file named LICENSE in libyami top level).

But building system tries to match this against
e3fc50.. which appears to be md5sum of libyami-utils/LICENSE

**Comment by rojkov** [comment]
Indeed. The licenses' wordings differ only with the type of brackets used for placeholders for some reason.
Updated md5sum and force pushed.

**Comment by laxigithub** [comment]
VP9 decode is not enabled with this libyami build. could you please configure libyami with the following options:
--enable-vp8enc --enable-vp9dec

**Comment by rojkov** [comment]
Enabled vp8env and vp9dec. Force pushed.

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
Closing as obsolete. new gst-vaapi got merged.

**Pull request closed without merging**
