### PR TITLE
CI and build scripts: Improve compatibility by avoiding -v tests

### PR DESCRIPTION
**Pull request by okartau**
We used some bash-specific is-var-defined testing via -v VAR
which does not work in older bash and in other shells,
also indirect use of variable name as variable is bash-specific
so the code is changed to avoid these specific features.
Functionally should be equal to previous state of scripts.

### CODE REVIEW

**Comment by mythi** [comment]
PR #44 has conflicting changes. I have #44 queued in #54 which I'd like to process next.

**Comment by okartau** [comment]
nothing in this PR is urgent, it does not change result, improves portability of scripts. I can rebase to match later state

**Comment by mythi** [comment]
this can be rebased now

**Comment by mythi** [comment]
the changes are tested in previous builds so merging

**Pull request merged**
