### PR TITLE
Update beignet SRCREV to latest HEAD

### PR DESCRIPTION
**Pull request by jlaako**
In order to make beignet compile with on host systems with gcc-6, update
is needed.

Signed-off-by: Jussi Laako jussi.laako@linux.intel.com

### CODE REVIEW

**Comment by okartau** [comment]
test this please

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
@jlaako we've received an additional request to integrate beignet 1.2.0. Can you adapt this PR to meet that request?

**Comment by jlaako** [comment]
@mythi current beignet seems to be broken in our infra...

**Comment by mythi** [comment]
@jlaako do you mean it builds fine locally but fails in CI?

**Comment by jlaako** [comment]
@mythi I don't know yet if it builds locally, because my local builds have been blocked by build breakage elsewhere (openssl, etc).

**Comment by jlaako** [comment]
This is already coming from oe-core, so close this as obsolete.

**Pull request closed without merging**
