### PR TITLE
Audio I2S

### PR DESCRIPTION
**Pull request by mythi**

### CODE REVIEW

**Comment by mythi** [comment]
test this please

**Comment by mythi** [comment]
@jlaako I've added all audio changes in this PR. Can you help with the review

**Comment by jlaako** [comment]
Looks good to me, this should hopefully make the I2S support complete with support for WM8998 codec.

**Comment by mythi** [comment]
@jlaako thanks. I also added 317a4d0 in this PR to speed up integration. Any feedback to that?

**Comment by jlaako** [comment]
@mythi I think that is good to avoid nasty initial user experience. If someone wants it, they can put it back. It may work for the cases where the devices connected to the USB are known upfront. So it is good to keep it available in this way.

**Pull request merged**
