### PR TITLE
Add meta-intel-realsense layer

### PR DESCRIPTION
**Pull request by avishaymahluf**

### CODE REVIEW

**Comment by mythi** [comment]
retest this please

**Comment by avishaymahluf** [comment]
test this please

**Comment by avishaymahluf** [comment]
test this please

**Comment by mythi** [comment]
@avishaymahluf this PR hits a CI error in fetching clang from the sstate. We're debugging it at the moment.

**Comment by avishaymahluf** [comment]
@mythi Looks like the current build did not encountered the sstate issue.

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
@avishaymahluf before I merge please make the following changes/clean-ups:
- rebase to master
- drop all libunwind/libatomic-ops related changes
- re-organize commits. These three commits are enough:

1) enable the submodule and directly pull the latest (`319f55742d9b77ff964d7fb10f61e01ffa668572`)
2) "remove librealsense recipes from meta-ostro-xt"
3) enable meta-realsense `c5395ca3ccbe24f6d6ad84e116109d301ec73dc0` without .gitmodules change

**Comment by mythi** [comment]
retest this please

**Comment by mythi** [comment]
retest this please

**Pull request merged**
