### PR TITLE
Add Crosswalk layer

### PR DESCRIPTION
**Pull request by huningxin**

### CODE REVIEW

**Comment by okartau** [comment]
CI tester failed but did not show the actual error:
ERROR: Layer directory '/srv/jenkins/workspace/builder-slot-2/ostro-os/../meta-crosswalk' does not exist! Please check BBLAYERS in /srv/jenkins/workspace/builder-slot-2/build/conf/bblayers.conf

**Comment by huningxin** [comment]
@okartau , thanks for the sharing the error message! Just updated the PR. The CI tester starts to compile now.

**Comment by huningxin** [comment]
Rebased the PR to ostro-os-xt master https://github.com/ostroproject/ostro-os-xt/commit/92c29a08dfe76ba18671c5a32b599434d669c028.

**Comment by huningxin** [comment]
Updated the PR to meta-crosswalk master https://github.com/crosswalk-project/meta-crosswalk/commit/23141eb7ccf64fa316f5ec2a9bf0244fbab818ff.

**Comment by huningxin** [comment]
Updated the PR to meta-crosswalk master https://github.com/crosswalk-project/meta-crosswalk/commit/f8a2cb40dbf7a34c6235813b54eca886543c7fab

**Comment by okartau** [comment]
test this please

**Comment by mythi** [comment]
@huningxin do you still need this test-build?

**Comment by huningxin** [comment]
we don't need this. I will close it. Thanks!

**Pull request closed without merging**
